### ISSUE TITLE
label text "Show more/Show less" won't work with multi div in one page

### ISSUE THREAD

**Issue by wavecheng** [JoanClaret/jquery-dynamic-max-height#1]
test html code:
==============================================
        <section class="container">
            <h1>Dynamic max height plugin for jQuery <span>with CSS animation</span></h1>
            
            <div class="dynamic-max-height" data-maxheight="70">
                <div class="dynamic-wrap">
                  <p> My life fades. The vision dims. All that remains are memories. I remember a time of chaos... ruined dreams... this wasted land. But most of all, I remember The Road Warrior. The man we called "Max." To understand who he was, you have to go back to another time... when the world was powered by the black fuel... and the desert sprouted great cities of pipe and steel. Gone now... swept away. For reasons long forgotten, two mighty warrior tribes went to war, and touched off a blaze which engulfed them all. Withou</p>
                </div>
                <div class="align-center">
                    <a class="dynamic-show-more" href="javascript:void(0);" title="Read more" data-replace-text="Show less">Read more</a>
                </div>
            </div>
            <div class="dynamic-max-height" data-maxheight="70">
                <div class="dynamic-wrap">
                  <p> My life fades. The vision dims. All that remains are memories. I remember a time of chaos... ruined dreams... this wasted land. But most of all, I remember The Road Warrior. The man we called "Max." To understand who he was, you have to go back to another time... when the world was powered by the black fuel... and the desert sprouted great cities of pipe and steel. Gone now... swept away. For reasons long forgotten, two mighty warrior tribes went to war, and touched off a blaze which engulfed them all. Without</p>
                </div>
                <div class="align-center">
                    <a class="dynamic-show-more" href="javascript:void(0);" title="more" data-replace-text="less">Read more</a>
                </div>
            </div>           
        </section>

**Comment by JoanClaret** [comment]
you're right, something is wrong, but we have it working fine in Appszoom, so let me take a look and i'll tell you something asap.

**Comment by JoanClaret** [comment]
I've been refactoring the plugin. Now is fixed.

PD: in order to improve the code quality, class name has been changed.

Cheers
Joan
