### ISSUE TITLE
VanillaJS version

### ISSUE THREAD

**Issue by pinceladasdaweb** [JoanClaret/jquery-dynamic-max-height#2]
Not really a problem, but I would like to inform you that just by creating a version of your plugin with pure JavaScript: https://github.com/pinceladasdaweb/DynamicMaxHeight

**Comment by JoanClaret** [comment]
Looks awesome mate. Congratulations!
I'll put a link to your repo tomorrow.

**Comment by pinceladasdaweb** [comment]
Thanks.
