### ISSUE TITLE
add button hide css in your css file 

### ISSUE THREAD

**Issue by Dkboss9033** [JoanClaret/jquery-dynamic-max-height#3]
Hi Awesome work in this plugin buddy

Thanks For this, its really helpful.

there is only 2 line CSS Missing in your CSS File is when content height is smaller then max-height then button hide otherwise show.

add below css
--------------------------------------------------------------------
.js-dynamic-height button.js-dynamic-show-hide {display:none}
.js-dynamic-height.dynamic-height-active button.js-dynamic-show-hide {display:block}
----------------------------------------------------------------------
otherwise All just awesome 

Thanks once again

**Comment by JoanClaret** [comment]
Hi there!
thanks for your comments

the plugin should show/hide the button using this selectors:

```
.dynamic-height-active .dynamic-show-more {
  display: inline-block;
}

.dynamic-show-more {
  display: none;
}
```

you can find it in the README file.
Cheers!
